stub BLEMultipeerTransport
does not compile, committing so we can see how the Multipeer APIs look in AirShare

Undefined symbols for architecture arm64:
  "_OBJC_METACLASS_$_BLETransport", referenced from:
      _OBJC_METACLASS_$_BLEMultipeerTransport in BLEMultipeerTransport.o
  "_OBJC_CLASS_$_BLETransport", referenced from:
      _OBJC_CLASS_$_BLEMultipeerTransport in BLEMultipeerTransport.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)